"""Enums and shared constants."""
from enum import Enum


class ChatIntent(str, Enum):
    # Core queries
    GET_DAMAGE_FOR_LOCATION = "GET_DAMAGE_FOR_LOCATION"
    GET_DAMAGE_DISTRIBUTION = "GET_DAMAGE_DISTRIBUTION"
    GET_BUILDINGS_BY_DAMAGE = "GET_BUILDINGS_BY_DAMAGE"
    GET_SCENE_SUMMARY = "GET_SCENE_SUMMARY"
    GET_BUILDING_DETAILS = "GET_BUILDING_DETAILS"

    # Ranking
    GET_TOP_K_DAMAGE = "GET_TOP_K_DAMAGE"
    GET_HIGHEST_CONFIDENCE = "GET_HIGHEST_CONFIDENCE"
    RANK_CITIES_BY_DAMAGE = "RANK_CITIES_BY_DAMAGE"

    # Evaluation
    GET_MODEL_PERFORMANCE = "GET_MODEL_PERFORMANCE"
    GET_MISCLASSIFICATIONS = "GET_MISCLASSIFICATIONS"
    GET_ACCURACY_BY_DAMAGE = "GET_ACCURACY_BY_DAMAGE"
    GET_FAILURE_CASES = "GET_FAILURE_CASES"

    # Confidence
    GET_CONFIDENCE_ANALYSIS = "GET_CONFIDENCE_ANALYSIS"
    GET_CONFIDENCE_OUTLIERS = "GET_CONFIDENCE_OUTLIERS"

    # Comparison
    COMPARE_LOCATIONS = "COMPARE_LOCATIONS"
    COMPARE_BUILDINGS = "COMPARE_BUILDINGS"

    # Meta / misc
    GET_DATASET_HEALTH = "GET_DATASET_HEALTH"
    FILTER_BY_STATUS = "FILTER_BY_STATUS"
    GET_MODEL_EXPLANATION = "GET_MODEL_EXPLANATION"
    GET_RANDOM_BUILDING = "GET_RANDOM_BUILDING"

    # Fallback
    OUT_OF_SCOPE = "OUT_OF_SCOPE"


DAMAGE_LEVELS = ["no-damage", "minor-damage", "major-damage", "destroyed"]